"""empty message

Revision ID: aa28789b1d1a
Revises: 
Create Date: 2020-10-16 16:48:21.451353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa28789b1d1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialties_name'), 'specialties', ['name'], unique=False)
    op.create_table('status_consults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_consults_name'), 'status_consults', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('login', sa.String(length=60), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consult_date', sa.DateTime(), nullable=True),
    sa.Column('id_patient', sa.Integer(), nullable=True),
    sa.Column('id_status_consult', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_patient'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['id_status_consult'], ['status_consults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupation_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('id_specialty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_specialty'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupation_areas_name'), 'occupation_areas', ['name'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('id_consult', sa.Integer(), nullable=True),
    sa.Column('id_specialty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_consult'], ['consults.id'], ),
    sa.ForeignKeyConstraint(['id_specialty'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_full_name'), 'doctors', ['full_name'], unique=False)
    op.create_table('secretaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('consult_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consult_id'], ['consults.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secretaries')
    op.drop_index(op.f('ix_doctors_full_name'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_occupation_areas_name'), table_name='occupation_areas')
    op.drop_table('occupation_areas')
    op.drop_table('consults')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_status_consults_name'), table_name='status_consults')
    op.drop_table('status_consults')
    op.drop_index(op.f('ix_specialties_name'), table_name='specialties')
    op.drop_table('specialties')
    op.drop_table('patients')
    # ### end Alembic commands ###
